### ISSUE TITLE
distance popup window annoyance

### ISSUE THREAD

**Issue by shinkolobwe** [GIScience/ors-map-client#100] opened 2021-03-05 11:43 UTC
Hello,
a comment on the distance popup window: I find this quite annoying. It pops up at the place where a route was just modified and therefore obscures exactly the place where one would be most interested in seeing additional points or the map, or to see the new route. I also do not see much added value from the popup in the middle of the map. It could well be placed at another location of the GUI.
Best wishes
Christian

**Comment by amoncaldas** [comment] 2021-03-05 11:56
Hey @shinkolobwe 
Thanks for your feedback.
The route distance and duration popup is necessary to show a summary of the route to the user. It can be closed and then the user will be able inspect any map detail. It also provides the profile that is being used (via icon). 

You have to consider that there are many possible scenarios: 
- users on mobile devices or low resolution will not have the side bar open by default. So if they use context actions to calculate a route, they will not have the basic information about the route. 
- Another case is when the app URL (with a route calculated) is shared and the route was not defined by the user who is viewing it. In this case the essential info about the route must be clear: profile, distance and duration. 

We use leaflet and the polyline popup to show the route details, so it makes sense that the details are visually linked to the element (route polyline) drawn on the map and not in another location. Although it is not determining, I could also argue that other commercial map clients also show this route summary popup. So we assume the users are already used to it.

I appreciate your comments and willing to contribute, but in this case we will keep it. Maybe if more users support your point then we can reevaluate it in the near future.
Best wishes
Amon

**Comment by shinkolobwe** [comment] 2021-03-08 19:08
Hi Amon
perhaps you can agree that the route shown in the attachment is pretty hidden, not what the average user would desire from the software or the service. I think with all the background efforts, you are damaging quite a lot of utility here, without any real necessity to do so. The popup can be placed at another location, distant from the route, without losing anything. 
Best wishes
Christian
![Screenshot_2021-03-08 ORS Maps](https://user-images.githubusercontent.com/80096521/110368828-d8036080-8049-11eb-8f45-b9bc122a61b1.png)

**Comment by amoncaldas** [comment] 2021-03-10 11:17
Hey Christian.
Thanks for getting back and for the example. At some point of development the route popup was not being displayed automatically after a route (re)calculation, but then it was demanded by some people. We must have in mind that different people might have different expectations and sometimes they are conflicting. 

Since you didn't provide the exact locations you used in your example, I could not reproduce the exact route, but I calculated a similar one. For me, the proportion between the route popup and the route displayed on the map are different, for both: mobile and desktop. In the examples I'm attaching the route is quite clear as well as most of the elements on the map. It is also important to remember that the popup is just displayed when a fresh route is calculated, so the user can close it if s/he wants. 

I understand your point. Is is very clear that you don't consider it necessary. So, I think that the best thing to do is to wait to see if other users back your view. If that happens, then we could add an option that would control if the popup is displayed or not when a fresh route is calculated.

Best regards,

<img width="1439" alt="Capture d’écran 2021-03-10 à 12 09 08" src="https://user-images.githubusercontent.com/13475791/110621237-42c3b180-819a-11eb-9a84-1e34411a5a59.png">
<img width="354" alt="Capture d’écran 2021-03-10 à 12 09 31" src="https://user-images.githubusercontent.com/13475791/110621251-47886580-819a-11eb-9dd1-05727d911950.png">

**Closed by amoncaldas** 2021-03-10 11:17 UTC
Labels: suggestion, wontfix
