### ISSUE TITLE
FR: Ability to use optimization endpoint

### ISSUE THREAD

**Issue by thibaultmol** [GIScience/ors-map-client#68] opened 2020-12-22 18:49 UTC
Being able to optimize a route from within this user friendly client would be a very useful addition.

**Comment by amoncaldas** [comment] 2021-02-10 18:21
Hey @thibaultmol . Could you please give us more details about the optimization feature you would like see in the app? thanks

**Comment by thibaultmol** [comment] 2021-02-12 14:04
I know that the ORS has an api for route optimizations. But it requires you to use the api directly, which a lot of people can't do (becaues of complexity). So being able to do it within the new map client would be a solution.

**Comment by TheGreatRefrigerator** [comment] 2023-03-30 21:38
duplicate of #34

**Closed by TheGreatRefrigerator** 2023-03-30 21:38 UTC
Labels: feature
